// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    foods,
    foodLogs,
    exercises,
    exerciseLogs,
    waterLogs,
    weightLogs,
    userProfile,
    metadata,
  ];
  late final Shape0 foods = Shape0(
    source: i0.VersionedTable(
      entityName: 'foods',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 foodLogs = Shape1(
    source: i0.VersionedTable(
      entityName: 'food_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 exercises = Shape2(
    source: i0.VersionedTable(
      entityName: 'exercises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_3, _column_27, _column_28],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 exerciseLogs = Shape3(
    source: i0.VersionedTable(
      entityName: 'exercise_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_17,
        _column_29,
        _column_30,
        _column_31,
        _column_26,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 waterLogs = Shape4(
    source: i0.VersionedTable(
      entityName: 'water_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_17, _column_32, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 weightLogs = Shape5(
    source: i0.VersionedTable(
      entityName: 'weight_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_17, _column_33, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 userProfile = Shape6(
    source: i0.VersionedTable(
      entityName: 'user_profile',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 metadata = Shape7(
    source: i0.VersionedTable(
      entityName: 'metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_50, _column_51],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get brand =>
      columnsByName['brand']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get category =>
      columnsByName['category']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get caloriesPer100g =>
      columnsByName['calories_per100g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get proteinPer100g =>
      columnsByName['protein_per100g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get carbsPer100g =>
      columnsByName['carbs_per100g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fatPer100g =>
      columnsByName['fat_per100g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fiberPer100g =>
      columnsByName['fiber_per100g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get sugarPer100g =>
      columnsByName['sugar_per100g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get sodiumPer100mg =>
      columnsByName['sodium_per100mg']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get defaultServingG =>
      columnsByName['default_serving_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get servingDescription =>
      columnsByName['serving_description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isGlutenFree =>
      columnsByName['is_gluten_free']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get glutenStatus =>
      columnsByName['gluten_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isCustom =>
      columnsByName['is_custom']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get seedKey =>
      columnsByName['seed_key']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'PRIMARY KEY AUTOINCREMENT',
      ),
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'brand',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'category',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_4(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'calories_per100g',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_5(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'protein_per100g',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_6(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'carbs_per100g',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_7(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'fat_per100g',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_8(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'fiber_per100g',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_9(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'sugar_per100g',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_10(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'sodium_per100mg',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_11(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'default_serving_g',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('100.0'),
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'serving_description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_gluten_free',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_14(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'gluten_status',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL DEFAULT \'unknown\' CHECK(gluten_status IN (\'gluten_free\',\'contains_gluten\',\'may_contain\',\'unknown\'))',
  defaultValue: const CustomExpression('\'unknown\''),
);
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_custom',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'seed_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mealType =>
      columnsByName['meal_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get foodId =>
      columnsByName['food_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get quantityG =>
      columnsByName['quantity_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get calories =>
      columnsByName['calories']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get protein =>
      columnsByName['protein']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get carbs =>
      columnsByName['carbs']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fat =>
      columnsByName['fat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get glutenStatus =>
      columnsByName['gluten_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get loggedAt =>
      columnsByName['logged_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_18(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'meal_type',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK(meal_type IN (\'breakfast\',\'lunch\',\'dinner\',\'snacks\'))',
);
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'food_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES foods (id)',
      ),
    );
i1.GeneratedColumn<double> _column_20(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'quantity_g',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_21(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'calories',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_22(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'protein',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_23(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'carbs',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_24(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'fat',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'gluten_status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'unknown\''),
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'logged_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get category =>
      columnsByName['category']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get metValue =>
      columnsByName['met_value']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<double> _column_27(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'met_value',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get exerciseId =>
      columnsByName['exercise_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationMinutes =>
      columnsByName['duration_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get caloriesBurned =>
      columnsByName['calories_burned']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get loggedAt =>
      columnsByName['logged_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'exercise_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES exercises (id)',
      ),
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_minutes',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<double> _column_31(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'calories_burned',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get amountMl =>
      columnsByName['amount_ml']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get loggedAt =>
      columnsByName['logged_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'amount_ml',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get weightKg =>
      columnsByName['weight_kg']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get loggedAt =>
      columnsByName['logged_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<double> _column_33(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'weight_kg',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dateOfBirth =>
      columnsByName['date_of_birth']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gender =>
      columnsByName['gender']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get heightCm =>
      columnsByName['height_cm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get weightKg =>
      columnsByName['weight_kg']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get activityLevel =>
      columnsByName['activity_level']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get goalType =>
      columnsByName['goal_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get calorieTarget =>
      columnsByName['calorie_target']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get proteinTargetG =>
      columnsByName['protein_target_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get carbsTargetG =>
      columnsByName['carbs_target_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fatTargetG =>
      columnsByName['fat_target_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get waterTargetMl =>
      columnsByName['water_target_ml']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isGlutenFree =>
      columnsByName['is_gluten_free']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dbVersion =>
      columnsByName['db_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get onboardingComplete =>
      columnsByName['onboarding_complete']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('1'),
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'date_of_birth',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'gender',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK(gender IN (\'male\',\'female\',\'other\'))',
    );
i1.GeneratedColumn<double> _column_38(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'height_cm',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_39(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'weight_kg',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<String> _column_40(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'activity_level',
  aliasedName,
  true,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'CHECK(activity_level IN (\'sedentary\',\'lightly_active\',\'moderately_active\',\'very_active\'))',
);
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'goal_type',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'CHECK(goal_type IN (\'lose\',\'maintain\',\'gain\'))',
    );
i1.GeneratedColumn<double> _column_42(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'calorie_target',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_43(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'protein_target_g',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_44(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'carbs_target_g',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_45(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'fat_target_g',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'water_target_ml',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('2000'),
    );
i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_gluten_free',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'db_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'onboarding_complete',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('0'),
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    foods,
    foodLogs,
    exercises,
    exerciseLogs,
    waterLogs,
    weightLogs,
    userProfile,
    metadata,
  ];
  late final Shape0 foods = Shape0(
    source: i0.VersionedTable(
      entityName: 'foods',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 foodLogs = Shape8(
    source: i0.VersionedTable(
      entityName: 'food_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_17,
        _column_18,
        _column_19,
        _column_52,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 exercises = Shape2(
    source: i0.VersionedTable(
      entityName: 'exercises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_3, _column_27, _column_28],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 exerciseLogs = Shape9(
    source: i0.VersionedTable(
      entityName: 'exercise_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_17,
        _column_29,
        _column_53,
        _column_30,
        _column_31,
        _column_26,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 waterLogs = Shape4(
    source: i0.VersionedTable(
      entityName: 'water_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_17, _column_32, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 weightLogs = Shape5(
    source: i0.VersionedTable(
      entityName: 'weight_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_17, _column_33, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 userProfile = Shape6(
    source: i0.VersionedTable(
      entityName: 'user_profile',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 metadata = Shape7(
    source: i0.VersionedTable(
      entityName: 'metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_50, _column_51],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mealType =>
      columnsByName['meal_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get foodId =>
      columnsByName['food_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get foodName =>
      columnsByName['food_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get quantityG =>
      columnsByName['quantity_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get calories =>
      columnsByName['calories']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get protein =>
      columnsByName['protein']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get carbs =>
      columnsByName['carbs']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fat =>
      columnsByName['fat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get glutenStatus =>
      columnsByName['gluten_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get loggedAt =>
      columnsByName['logged_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'food_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'\''),
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get exerciseId =>
      columnsByName['exercise_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get exerciseName =>
      columnsByName['exercise_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get durationMinutes =>
      columnsByName['duration_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get caloriesBurned =>
      columnsByName['calories_burned']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get loggedAt =>
      columnsByName['logged_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'exercise_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'\''),
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
